sudo: false

language: java
jdk: oraclejdk7

# Disable cache to test dependency resolution
#cache:
#  directories:
#    - '$HOME/.m2/repository'

script:
  #- mvn clean install -B && mvn clean -B
  - mvn clean install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/952357dbd9d3cea70fd5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
