name: ${pluginName}
authors: [${pluginAuthors}]
website: ${project.url}
description: ${project.description}
main: ${mainClass}
version: ${project.version}-b${buildNumber}
softdepend:
    - Vault
    - PermissionsBukkit
    - PermissionsEX
    - EssentialsGroupManager
    - Multiverse-Core
    - Essentials
    - EssentialsSpawn
    - ProtocolLib
commands:
    register:
        description: Register an account
        usage: /register password confirmpassword
        aliases: reg
    login:
        description: Login into a account
        usage: /login password
        aliases: l
    changepassword:
        description: Change password of a account
        usage: /changepassword oldPassword newPassword
    logout:
        description: Logout
        usage: /logout
    unregister:
        description: unregister your account
        usage: /unregister password
    authme:
        description: AuthMe op commands
        usage: '/authme reload|register playername password|changepassword playername password|unregister playername|version'
    email:
        description: Add Email or recover password
        usage: '/email add your@email.com your@email.com|change oldEmail newEmail|recovery your@email.com'
    captcha:
        description: Captcha
        usage: /captcha theCaptcha
    converter:
        description: Converter from different other auth plugins
        usage: /converter <datatype>
permissions:
    authme.admin.*:
        description: Give access to all admin commands.
        children:
            authme.admin.accounts: true
            authme.admin.changemail: true
            authme.admin.changepassword: true
            authme.admin.converter: true
            authme.admin.firstspawn: true
            authme.admin.forcelogin: true
            authme.admin.getemail: true
            authme.admin.getip: true
            authme.admin.lastlogin: true
            authme.admin.purge: true
            authme.admin.purgebannedplayers: true
            authme.admin.purgelastpos: true
            authme.admin.register: true
            authme.admin.reload: true
            authme.admin.setfirstspawn: true
            authme.admin.setspawn: true
            authme.admin.spawn: true
            authme.admin.switchantibot: true
            authme.admin.unregister: true
    authme.player.*:
        description: Permission to use all player (non-admin) commands.
        children:
            authme.player.allow2accounts: true
            authme.player.bypassantibot: true
            authme.player.bypassforcesurvival: true
            authme.player.canbeforced: true
            authme.player.captcha: true
            authme.player.changepassword: true
            authme.player.email.add: true
            authme.player.email.change: true
            authme.player.email.recover: true
            authme.player.login: true
            authme.player.logout: true
            authme.player.register: true
            authme.player.seeotheraccounts: true
            authme.player.unregister: true
            authme.player.vip: true
