version: 2
jobs:
    build_and_test_jdk8:
        working_directory: ~/authmereloaded-jdk8
        docker:
            - image: maven:3.6.0-jdk-8
        environment:
                MAVEN_OPTS: -Xmx2048m
        steps:
            - checkout
            - run: mvn -B clean package
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/*.jar
    build_and_test_jdk11:
        working_directory: ~/authmereloaded-jdk11
        docker:
            - image: maven:3.6.0-jdk-11
        environment:
            MAVEN_OPTS: -Xmx2048m
        steps:
            - checkout
            - run: mvn -B clean package
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/*.jar
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_and_test_jdk8
            - build_and_test_jdk11
