version: 2
jobs:
    build_and_test_jdk8:
        working_directory: ~/authmereloaded-jdk8
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
                MAVEN_OPTS: -Xmx2048m
        steps:
            - checkout
            - restore_cache:
                keys:
                    - authmereloaded-{{ checksum "pom.xml" }}
                    - authmereloaded-
            - run: mvn -T 2 -B dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: authmereloaded-{{ checksum "pom.xml" }}
            - run: mvn -T 2 -B package
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/*.jar
    build_and_test_jdk11:
        working_directory: ~/authmereloaded-jdk11
        docker:
            - image: openjdk:11.0.1-jdk-sid
        environment:
            MAVEN_OPTS: -Xmx2048m
        steps:
            - checkout
            - restore_cache:
                keys:
                    - authmereloaded-{{ checksum "pom.xml" }}
                    - authmereloaded-
            - run: mvn -T 2 -B dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: authmereloaded-{{ checksum "pom.xml" }}
            - run: mvn -T 2 -B package
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/*.jar
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_and_test_jdk8
            - build_and_test_jdk11
